# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['src/alphacam_cli/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'win32com',
        'win32com.client',
        'win32com.client.gencache',
        'pythoncom',
        'typer',
        'rich',
        'rich.table',
        'rich.console',
        'rich.progress',
        'rich.traceback',
        # Dynamic subcommand modules loaded via importlib
        'alphacam_cli.cli.connect',
        'alphacam_cli.cli.drawing',
        'alphacam_cli.cli.tool',
        'alphacam_cli.cli.mill',
        'alphacam_cli.cli.nc',
        'alphacam_cli.cli.batch',
        'alphacam_cli.cli.diagnose',
        'alphacam_cli.cli.nest',
        'alphacam_cli.cli.post',
        'alphacam_cli.core.config',
        'alphacam_cli.core.logger',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='alphacam',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
