# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['src/alphacam_cli/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[('scripts', 'scripts')],
    hiddenimports=[
        'win32com',
        'win32com.client',
        'win32com.client.gencache',
        'pythoncom',
        'typer',
        'rich',
        'rich.table',
        'rich.console',
        'rich.progress',
        'rich.traceback',
        # Dynamic subcommand modules loaded via importlib (main.py _SUBCOMMANDS)
        'alphacam_cli.cli.connect',
        'alphacam_cli.cli.drawing',
        'alphacam_cli.cli.tool',
        'alphacam_cli.cli.mill',
        'alphacam_cli.cli.nc',
        'alphacam_cli.cli.batch',
        'alphacam_cli.cli.diagnose',
        'alphacam_cli.cli.nest',
        'alphacam_cli.cli.post',
        'alphacam_cli.cli.reports',
        'alphacam_cli.cli.ncmanager',
        'alphacam_cli.cli.autostyle',
        'alphacam_cli.cli.cdm',
        # Core modules (imported lazily from subcommands)
        'alphacam_cli.core.config',
        'alphacam_cli.core.logger',
        'alphacam_cli.core.application',
        'alphacam_cli.core.cdm_db',
        'alphacam_cli.core.drawing',
        'alphacam_cli.core.events',
        'alphacam_cli.core.machining',
        'alphacam_cli.core.nesting',
        'alphacam_cli.core.tool',
        # COM / gateway modules
        'alphacam_cli.com.constants',
        'alphacam_cli.com.manager',
        'alphacam_cli.gateway.client',
        'alphacam_cli.gateway.protocol',
        'alphacam_cli.gateway.remote',
        'alphacam_cli.gateway.server',
        'alphacam_cli.gateway.service',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='alphacam',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
