PROG_IDS = [
    "Ar5axaps.Application",
    "am5axaps.Application",
    "aroutaps.Application",
]

# Tool types (from acAPI.bas)
ACAM_TOOL_SQUARE = 0
ACAM_TOOL_BULL = 1
ACAM_TOOL_BALL = 2
ACAM_TOOL_DRILL = 3
ACAM_TOOL_TAP = 4
ACAM_TOOL_USER = 5
ACAM_TOOL_WHEEL = 6

# Surface MC actions
ACAM_SURFACE_MC_ROUGHING = 0
ACAM_SURFACE_MC_FINISHING = 1
ACAM_SURFACE_MC_TOOLSIDE = 2
ACAM_SURFACE_MC_PENCIL = 3

# Pocket types
ACAM_POCKET_CONTOUR = 0
ACAM_POCKET_ZIGZAG = 1
ACAM_POCKET_SPIRAL = 2
ACAM_POCKET_TRUE_SPIRAL = 3
ACAM_POCKET_PARALLEL = 4

# ToolInOut
ACAM_TOOL_OUTSIDE = -1
ACAM_TOOL_INSIDE = 1
ACAM_TOOL_CENTER = 0

# Drill types
ACAM_DRILL = 0
ACAM_TAP = 1
ACAM_BORE = 2
ACAM_PECK = 3

# Saw corner types (AcamSawCornerType, names verified via Interop.AlphaCAMMill.dll;
# numeric values to verify against Router typelib)
ACAM_SAW_CUT_ON = 1
ACAM_SAW_CUT_PAST = 2
ACAM_SAW_CUT_TO = 3

# Saw head position (AcamSawHeadPosition)
ACAM_SAW_HEAD_LEFT = 0
ACAM_SAW_HEAD_RIGHT = 1

# Engrave types (AcamEngraveType)
ACAM_ENGRAVE_GEOMETRIES = 0
ACAM_ENGRAVE_GUIDE_LINES_APPROX = 1
ACAM_ENGRAVE_GUIDE_LINES_EXACT = 2
ACAM_ENGRAVE_SIMPLE_EXACT = 3

# NC output destinations
ACAM_OUT_NC_FILE = 0
ACAM_OUT_NC_MACHINE = 1
ACAM_OUT_NC_BOTH = 2
ACAM_OUT_NC_ASK = -1

# Module letters
MODULE_MILL = 77  # 'M'
MODULE_ROUTER = 82  # 'R'
MODULE_LATHE = 76  # 'L'
MODULE_WIRE = 87  # 'W'
MODULE_FLAME = 70  # 'F'

# CAD units (Drawing.SaveIgesFile)
ACAM_UNITS_INCH = 0
ACAM_UNITS_METRIC = 1

# STL export type (Drawing.SaveStlFile)
ACAM_STL_TYPE_STL = 0
ACAM_STL_TYPE_SURFACES = 1
ACAM_STL_TYPE_PARASOLID = 2

# IGES/STEP translator types
ACAM_IGES_STD = 0
ACAM_IGES_ADV = 1
ACAM_IGES_VAL = 2
ACAM_STEP_SURFACES = 0
ACAM_STEP_SOLID = 1

# CAD input settings (App.CadInputSettings)
ACAM_DXF_SPECIAL_STANDARD = 0
ACAM_DXF_SPECIAL_CABINETS = 1
